
export const SUPABASE_URL = 'https://bacpduvlvymxvcdmtsvr.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhY3BkdXZsdnlteHZjZG10c3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1ODUwOTksImV4cCI6MjA3OTE2MTA5OX0.2t6S_dIexSjGpRaSFE1DkuazsIhF8dk57l8fVdZZgJk';
