/**
 * Supabase Database Types
 * 
 * This file should be generated by running:
 *   npm run gen:types
 * 
 * Or manually:
 *   npx supabase login
 *   npx supabase gen types typescript --project-id bacpduvlvymxvcdmtsvr > src/types/database.types.ts
 * 
 * For now, this is a placeholder. After running the generation command,
 * this file will contain the full Database type definition.
 */

export type Database = {
  public: {
    Tables: {
      // Types will be generated here
      [key: string]: {
        Row: Record<string, any>
        Insert: Record<string, any>
        Update: Record<string, any>
      }
    }
    Views: {
      [key: string]: {
        Row: Record<string, any>
      }
    }
    Functions: {
      [key: string]: {
        Args: Record<string, any>
        Returns: any
      }
    }
    Enums: {
      [key: string]: string
    }
  }
}

