
import React, { useEffect, useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { UserIcon, SparklesIcon } from '@/shared/components/icons';

const CompleteProfileModal: React.FC = () => {
    const { currentUser } = useAuth();
    const navigate = useNavigate();
    const location = useLocation();
    const [isOpen, setIsOpen] = useState(false);

    // Check if profile is incomplete
    useEffect(() => {
        if (!currentUser) {
            setIsOpen(false);
            return;
        }

        // Don't show on setup page or login page
        if (location.pathname === '/setup-profile' || location.pathname === '/login') {
            setIsOpen(false);
            return;
        }

        // Criteria for "Incomplete":
        // 1. Username starts with "user_" (auto-generated)
        // 2. Missing DNI
        // 3. Missing Phone
        const isAutoGeneratedUsername = currentUser.username && currentUser.username.startsWith('user_');
        const isMissingInfo = !currentUser.dni || !currentUser.phone;

        if (isAutoGeneratedUsername || isMissingInfo) {
            setIsOpen(true);
        } else {
            setIsOpen(false);
        }
    }, [currentUser, location.pathname]);

    const handleCompleteNow = () => {
        // Do NOT close modal locally, just navigate. 
        // The modal will close automatically once the route changes to /setup-profile due to the useEffect above.
        navigate('/setup-profile');
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black bg-opacity-90 z-[3000] flex justify-center items-center p-4 animate-fade-in backdrop-blur-md">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-md overflow-hidden relative transform transition-all scale-100">
                <div className="bg-gradient-to-r from-brand-primary to-blue-600 p-6 text-center text-white">
                    <div className="mx-auto bg-white/20 w-16 h-16 rounded-full flex items-center justify-center mb-3 backdrop-blur-sm">
                        <UserIcon className="h-8 w-8 text-white" />
                    </div>
                    <h2 className="text-xl font-bold mb-1">¡Bienvenido a Pets!</h2>
                    <p className="text-blue-100 text-sm">Para continuar, es obligatorio completar tu perfil.</p>
                </div>
                
                <div className="p-6 space-y-4">
                    <p className="text-gray-600 text-center text-sm leading-relaxed font-medium">
                        Para garantizar la seguridad de nuestra comunidad y poder reportar o ayudar con mascotas, necesitamos que verifiques tus datos.
                    </p>

                    <div className="bg-blue-50 p-3 rounded-lg border border-blue-100 text-sm text-blue-800 flex gap-3 items-start">
                        <SparklesIcon />
                        <p>Al completar tu perfil, aumentas la confianza de la comunidad y ayudas a encontrar mascotas más rápido.</p>
                    </div>

                    <div className="flex flex-col gap-3 mt-4">
                        <button 
                            onClick={handleCompleteNow}
                            className="w-full py-3 px-4 bg-brand-primary text-white font-bold rounded-lg hover:bg-brand-dark transition-colors shadow-md hover:shadow-lg transform hover:-translate-y-0.5"
                        >
                            Completar mi Perfil Ahora
                        </button>
                    </div>
                </div>
                {/* No close button provided intentionally to force completion */}
            </div>
        </div>
    );
};

export default CompleteProfileModal;
